[test_data]
git-tree-sha1 = "edcbcf8c48f822c5f23d2c4170c148d7db991bbe"
lazy = true

    [[test_data.download]]
    sha256 = "0fc22ea2f1f81adae7cc0cf55926be8e2f527ebfe5bc7208da1e880fc4c0115d"
    url = "https://github.com/maurergroup/Quoll.jl/releases/download/test-data-v0.4.0/test-data-v0.4.0.tar.gz"
