[test_data]
git-tree-sha1 = "0fa04aadb411dbb57180a9b6e6fb7ba6637eaa21"
lazy = true

    [[test_data.download]]
    sha256 = "9903847954cbd52ebe8d290da36fe5bc3e47da7ad812ccfce4b0f0b4cd769c87"
    url = "https://github.com/maurergroup/Quoll.jl/releases/download/test-data-v0.2.0/test-data-v0.2.0.tar.gz"
